# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  pullPolicy: Always
  repository: git.lab.kalvinov.com:5050/helloworld/ultraback

imagePullSecrets: 
- name: "regcred"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  portName: app
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
# livenessProbe: {}
# readynessProbe: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  VAR1: "val1"